### ISSUE TITLE
fn:amc no longer runs

### ISSUE THREAD

**Issue by gsparx** [filebot/filebot#14]
I'm seeing the following output when attempting to run fn:amc

```
FileNotFoundException: https://raw.githubusercontent.com/filebot/scripts/m1/amc.groovy
java.io.FileNotFoundException: https://raw.githubusercontent.com/filebot/scripts/m1/amc.groovy
	at net.filebot.web.WebRequest.fetch(WebRequest.java:123)
	at net.filebot.web.WebRequest.fetchIfModified(WebRequest.java:101)
	at net.filebot.web.CachedResource.fetchData(CachedResource.java:32)
	at net.filebot.web.CachedResource.fetchData(CachedResource.java:11)
	at net.filebot.web.AbstractCachedResource.fetch(AbstractCachedResource.java:137)
	at net.filebot.web.AbstractCachedResource.get(AbstractCachedResource.java:82)
	at net.filebot.cli.ArgumentProcessor$DefaultScriptProvider.fetchScript(ArgumentProcessor.java:210)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:82)
	at net.filebot.cli.ArgumentProcessor.process(ArgumentProcessor.java:116)
	at net.filebot.Main.main(Main.java:168)
Failure (°_°)
```
Apparently that file no longer exists. Can it be made available for download so we can reference it locally? I tried downloading the latest amc.groovy from github but got the following so it looks like its incompatible with my version of filebot

```
MissingMethodException: No signature of method: java.io.File.isMovie() is applicable for argument types: () values: []
Possible solutions: isFile(), isAudio(), isCase(java.lang.Object), isVideo(), memoize(), isArchive()
groovy.lang.MissingMethodException: No signature of method: java.io.File.isMovie() is applicable for argument types: () values: []
Possible solutions: isFile(), isAudio(), isCase(java.lang.Object), isVideo(), memoize(), isArchive()
	at Script1.forceMovie(Script1.groovy:61)
	at Script1$_run_closure51.doCall(Script1.groovy:329)
	at Script1.run(Script1.groovy:318)
	at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:61)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:82)
	at net.filebot.cli.ArgumentProcessor.process(ArgumentProcessor.java:116)
	at net.filebot.Main.main(Main.java:168)
Failure (°_°)
```

**Comment by rednoah** [comment]
No. You'll need latest version of FileBot.

**Comment by gsparx** [comment]
For anyone else with this problem the m1 version of the script can be found here 

https://gitlab.eecs.umich.edu/pjeschba/scripts/blob/m1/amc.groovy

It's working for me now with that version.

Great to see you're going the extra mile to support people using your software.  Not sure why it would have been a problem to put the file back up other than to force people to upgrade.

**Comment by rednoah** [comment]
I don't have time to support anything but the latest version. Seriously, who does?

Glad you're going the extra mile of trying the latest version before asking for support, or at least telling me which outdated version it is you're using. If it's using the m1 branch then it must be pretty old, like really really ancient old.

Also, congratulations on being vulnerable to compromised server or transport layer attacks. Wouldn't it be nice if FileBot shipped with it's own public key so it can check the digital signature for each script to make sure it's not been compromised? Oh wait, it does now! (just don't ask me since when) :P

**Comment by oddstr13** [comment]
What would be great, was if filebot didn't download the scripts off of the internet every single time it runs - then this wouldn't have been a problem in the first place.

@gsparx thanks! My scripts are back up and running now <3

**Comment by rednoah** [comment]
> What would be great, was if filebot didn't download the scripts off of the internet every single time it runs

It doesn't.

**Comment by oddstr13** [comment]
What's the switch to disable cache expiration then? Cause this is what made my sorting scripts randomly stop working.

**Comment by rednoah** [comment]
There's no switch for that. Never updating FileBot is what caused your scripts to stop working.
