### ISSUE TITLE
get java heap space error

### ISSUE THREAD

**Issue by ward0** [filebot/filebot#16]
logging:

Fetch subtitles for [/volume1/MOVIES/COUCH/Rogue.One.2016.1080p.BluRay.H264.AAC-RARBG]
Get [Dutch] subtitles for 1 files
Looking up subtitles by hash via OpenSubtitles
Looking up subtitles by name via OpenSubtitles
Java heap space
java.lang.OutOfMemoryError: Java heap space
	at org.tukaani.xz.lz.LZDecoder.<init>(Unknown Source)
	at org.tukaani.xz.LZMA2InputStream.<init>(Unknown Source)
	at org.tukaani.xz.LZMA2InputStream.<init>(Unknown Source)
	at org.tukaani.xz.LZMA2Decoder.getInputStream(Unknown Source)
	at org.tukaani.xz.BlockInputStream.<init>(Unknown Source)
	at org.tukaani.xz.SingleXZInputStream.read(Unknown Source)
	at org.tukaani.xz.XZInputStream.read(Unknown Source)
	at net.filebot.util.ByteBufferOutputStream.transferFrom(ByteBufferOutputStream.java:102)
	at net.filebot.util.ByteBufferOutputStream.transferFully(ByteBufferOutputStream.java:112)
	at net.filebot.util.ByteBufferOutputStream.transferFully(ByteBufferOutputStream.java:106)
	at net.filebot.CachedResource.lambda$getBytes$3(CachedResource.java:154)
	at net.filebot.CachedResource$$Lambda$22/5693387.transform(Unknown Source)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:99)
	at net.filebot.CachedResource$$Lambda$25/9690517.apply(Unknown Source)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$18(ReleaseInfo.java:489)
	at net.filebot.media.ReleaseInfo$$Lambda$81/11439726.get(Unknown Source)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getOpenSubtitlesIndex(ReleaseInfo.java:382)
	at net.filebot.WebServices$OpenSubtitlesClientWithLocalSearch.lambda$new$0(WebServices.java:181)
	at net.filebot.WebServices$OpenSubtitlesClientWithLocalSearch$$Lambda$146/24805171.get(Unknown Source)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.WebServices$OpenSubtitlesClientWithLocalSearch.search(WebServices.java:186)
	at net.filebot.subtitle.SubtitleUtilities.findProbableSearchResults(SubtitleUtilities.java:260)
	at net.filebot.subtitle.SubtitleUtilities.findSubtitlesByName(SubtitleUtilities.java:149)
	at net.filebot.cli.CmdlineOperations.getSubtitles(CmdlineOperations.java:709)
	at net.filebot.cli.CmdlineOperations.getMissingSubtitles(CmdlineOperations.java:780)
	at net.filebot.cli.ScriptShellBaseClass.getMissingSubtitles(ScriptShellBaseClass.java:376)

Failure (Â°_Â°)
Locking /volume1/@appstore/filebot-node/filebot.log
Illegal Argument: java.nio.file.NoSuchFileException: /root/subtitles=nld (subtitles=nld)

**Comment by rednoah** [comment]
Please run `filebot -script fn:sysinfo` and post the output.

**Comment by ward0** [comment]
meh out of memory, i know the solution.. closed

**Comment by T4mmi** [comment]
if you know the solution, might be nice to share it ...

**Comment by ward0** [comment]
@T4mmi see my solution: https://www.filebot.net/forums/viewtopic.php?t=3853

I have it as bookmark.. Every update i have to do this :(

**Comment by rednoah** [comment]
Not really. You just need to set `JAVA_OPTS` globally and then it'll work for any tool that uses `JAVA_OPTS` including all current and future versions of FileBot.

**Comment by T4mmi** [comment]
Thanks,
another way without modifying your global options (for devices with reduced memory that does not uses Java) you can just add the `-Xmx512m` option to the java call in filebot.sh (find it on your system, it's the last line) so you wont mess with your java installation.
