### ISSUE TITLE
I'm getting an error in FileBot 4.7.9 upon trying to rename files

### ISSUE THREAD

**Issue by stephen-marney** [filebot/filebot#25]
The error (below) occurs in 4.7.9 x86 and x64
The file FileBot.jar does, indeed, not contain com/sun/jna/win32-x86/jnidispatch.dll
4.7.8's FileBot.jar also does not include the .dll but it does not generate this error.
Does jnidispatch.dll need to be linked?

Native library (com/sun/jna/win32-x86/jnidispatch.dll) not found in resource path ([file:/C:/Program%20Files/FileBot/FileBot.jar])
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86/jnidispatch.dll) not found in resource path ([file:/C:/Program%20Files/FileBot/FileBot.jar])
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:921)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:881)
        at com.sun.jna.Native.<clinit>(Native.java:156)
        at com.sun.jna.platform.win32.Shell32.<clinit>(Shell32.java:45)
        at net.filebot.platform.windows.WinAppUtilities.setAppUserModelID(WinAppUtilities.java:16)
        at net.filebot.Main.startUserInterface(Main.java:225)
        at net.filebot.Main.lambda$main$1(Main.java:126)

**Comment by rednoah** [comment]
Please purchase FileBot on the Windows Store. You won't have these kinds of dependency issues if you use the Windows Store.
