### ISSUE TITLE
Failed to load series index: no protocol: @{url.data}/thetvdb.txt.xz

### ISSUE THREAD

**Issue by rayfun** [filebot/filebot#44]
Hi,

above error occurs with a fresh build from git master, built and packaged as debian package, installed and run with Java 9.
It occurs when a TV episode is dropped into the "Original files" area in "Rename" view and clicked "Match" -> "Episode Mode" -> "TheTVDB".

```
axel@ykela:~$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
axel@ykela:~$ echo $JAVA_HOME 
/usr/lib/jvm/java-9-oracle
axel@ykela:~$
```
```
axel@ykela:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```
```
axel@ykela:~$ filebot 
Failed to load series index: no protocol: @{url.data}/thetvdb.txt.xz
Failed to load series mappings: no protocol: @{url.data}/series-mappings.txt.xz
java.net.MalformedURLException: no protocol: @{url.data}/series-mappings.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.TransformedResource.get(Resource.java:54)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getSeriesMappings(ReleaseInfo.java:360)
	at net.filebot.media.MediaDetection.matchSeriesMappings(MediaDetection.java:470)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:356)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:326)
	at net.filebot.media.MediaDetection.mapSeriesNamesByFiles(MediaDetection.java:196)
	at net.filebot.ui.rename.EpisodeListMatcher.match(EpisodeListMatcher.java:99)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:921)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:917)

Failed to match folder structure: java.net.MalformedURLException: no protocol: @{url.data}/query-blacklist.txt.xz
Failed to strip release info: no protocol: @{url.data}/release-groups.txt.xz
java.net.MalformedURLException: no protocol: @{url.data}/release-groups.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getReleaseGroupPattern(ReleaseInfo.java:334)
	at net.filebot.media.ReleaseInfo.cleanRelease(ReleaseInfo.java:167)
	at net.filebot.media.MediaDetection.stripReleaseInfo(MediaDetection.java:1195)
	at net.filebot.media.MediaDetection.getUniqueQuerySet(MediaDetection.java:981)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:463)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:326)
	at net.filebot.media.MediaDetection.mapSeriesNamesByFiles(MediaDetection.java:196)
	at net.filebot.ui.rename.EpisodeListMatcher.match(EpisodeListMatcher.java:99)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:921)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:917)

Failed to strip release info: no protocol: @{url.data}/release-groups.txt.xz
java.net.MalformedURLException: no protocol: @{url.data}/release-groups.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getReleaseGroupPattern(ReleaseInfo.java:334)
	at net.filebot.media.ReleaseInfo.cleanRelease(ReleaseInfo.java:167)
	at net.filebot.media.MediaDetection.stripReleaseInfo(MediaDetection.java:1195)
	at net.filebot.media.MediaDetection.getUniqueQuerySet(MediaDetection.java:982)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:463)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:326)
	at net.filebot.media.MediaDetection.mapSeriesNamesByFiles(MediaDetection.java:196)
	at net.filebot.ui.rename.EpisodeListMatcher.match(EpisodeListMatcher.java:99)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:921)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:917)

Failed to strip release info: no protocol: @{url.data}/query-blacklist.txt.xz
java.net.MalformedURLException: no protocol: @{url.data}/query-blacklist.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getBlacklistPattern(ReleaseInfo.java:348)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.MediaDetection.stripBlacklistedTerms(MediaDetection.java:1218)
	at net.filebot.media.MediaDetection.getUniqueQuerySet(MediaDetection.java:983)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:463)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:326)
	at net.filebot.media.MediaDetection.mapSeriesNamesByFiles(MediaDetection.java:196)
	at net.filebot.ui.rename.EpisodeListMatcher.match(EpisodeListMatcher.java:99)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:921)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:917)

Failed to load series index: no protocol: @{url.data}/thetvdb.txt.xz
Failed to load series mappings: no protocol: @{url.data}/series-mappings.txt.xz
java.net.MalformedURLException: no protocol: @{url.data}/series-mappings.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.TransformedResource.get(Resource.java:54)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getSeriesMappings(ReleaseInfo.java:360)
	at net.filebot.media.MediaDetection.matchSeriesMappings(MediaDetection.java:470)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:356)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:326)
	at net.filebot.ui.rename.EpisodeListMatcher.matchEpisodeSet(EpisodeListMatcher.java:158)
	at net.filebot.ui.rename.EpisodeListMatcher.lambda$match$3(EpisodeListMatcher.java:106)

Failed to match folder structure: java.net.MalformedURLException: no protocol: @{url.data}/query-blacklist.txt.xz
Failed to strip release info: no protocol: @{url.data}/release-groups.txt.xz
java.net.MalformedURLException: no protocol: @{url.data}/release-groups.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getReleaseGroupPattern(ReleaseInfo.java:334)
	at net.filebot.media.ReleaseInfo.cleanRelease(ReleaseInfo.java:167)
	at net.filebot.media.MediaDetection.stripReleaseInfo(MediaDetection.java:1195)
	at net.filebot.media.MediaDetection.getUniqueQuerySet(MediaDetection.java:981)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:463)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:326)
	at net.filebot.ui.rename.EpisodeListMatcher.matchEpisodeSet(EpisodeListMatcher.java:158)
	at net.filebot.ui.rename.EpisodeListMatcher.lambda$match$3(EpisodeListMatcher.java:106)

Failed to strip release info: no protocol: @{url.data}/release-groups.txt.xz
java.net.MalformedURLException: no protocol: @{url.data}/release-groups.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getReleaseGroupPattern(ReleaseInfo.java:334)
	at net.filebot.media.ReleaseInfo.cleanRelease(ReleaseInfo.java:167)
	at net.filebot.media.MediaDetection.stripReleaseInfo(MediaDetection.java:1195)
	at net.filebot.media.MediaDetection.getUniqueQuerySet(MediaDetection.java:982)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:463)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:326)
	at net.filebot.ui.rename.EpisodeListMatcher.matchEpisodeSet(EpisodeListMatcher.java:158)
	at net.filebot.ui.rename.EpisodeListMatcher.lambda$match$3(EpisodeListMatcher.java:106)

Failed to strip release info: no protocol: @{url.data}/query-blacklist.txt.xz
java.net.MalformedURLException: no protocol: @{url.data}/query-blacklist.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getBlacklistPattern(ReleaseInfo.java:348)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.MediaDetection.stripBlacklistedTerms(MediaDetection.java:1218)
	at net.filebot.media.MediaDetection.getUniqueQuerySet(MediaDetection.java:983)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:463)
	at net.filebot.media.MediaDetection.detectSeriesNames(MediaDetection.java:326)
	at net.filebot.ui.rename.EpisodeListMatcher.matchEpisodeSet(EpisodeListMatcher.java:158)
	at net.filebot.ui.rename.EpisodeListMatcher.lambda$match$3(EpisodeListMatcher.java:106)

MalformedURLException: no protocol: @{url.data}/query-blacklist.txt.xz
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.net.MalformedURLException: no protocol: @{url.data}/query-blacklist.txt.xz
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.done(RenamePanel.java:936)
Caused by: java.util.concurrent.ExecutionException: java.net.MalformedURLException: no protocol: @{url.data}/query-blacklist.txt.xz
	at net.filebot.ui.rename.EpisodeListMatcher.match(EpisodeListMatcher.java:114)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:921)
	at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:917)
Caused by: java.net.MalformedURLException: no protocol: @{url.data}/query-blacklist.txt.xz
	at net.filebot.media.ReleaseInfo.lambda$resource$17(ReleaseInfo.java:482)
	at net.filebot.CachedResource.lambda$get$1(CachedResource.java:83)
	at net.filebot.Cache.computeIf(Cache.java:90)
	at net.filebot.CachedResource.get(CachedResource.java:82)
	at net.filebot.media.ReleaseInfo.lambda$resource$19(ReleaseInfo.java:482)
	at net.filebot.MemoizedResource.get(Resource.java:36)
	at net.filebot.media.ReleaseInfo.getStructureRootPattern(ReleaseInfo.java:257)
	at net.filebot.media.MediaDetection.isStructureRoot(MediaDetection.java:1031)
	at net.filebot.media.MediaDetection.listStructurePathTail(MediaDetection.java:1050)
	at net.filebot.media.MediaDetection.getStructurePathTail(MediaDetection.java:1060)
	at net.filebot.ui.rename.EpisodeListMatcher.getQueryInputMessage(EpisodeListMatcher.java:313)
	at net.filebot.ui.rename.EpisodeListMatcher.matchEpisodeSet(EpisodeListMatcher.java:165)
	at net.filebot.ui.rename.EpisodeListMatcher.lambda$match$3(EpisodeListMatcher.java:106)
```

**Comment by devster31** [comment]
I'm finding the same issue, I believe it's caused by the change in build system that happened around d7e32a761ed908d67d8ef86c34b35f6f59503d3b in the `java_1.8_backport` branch and following commits (or 10339686bcfe0c3076b76838ff772cdb377d27a1 for master). In the following commits you can find the `-Dvariable` available for use.

**Comment by mohammadg** [comment]
I ran into the same issue when I wanted to build Filebot from latest git.
The issue can be resolved by adding a few missing entries in the `app.properties` file.

Edit it and add:
```
# Missing info
url.data: https://app.filebot.net/data
apikey.fanart.tv: REMOVED
apikey.thetvdb: REMOVED
apikey.themoviedb: REMOVED
apikey.omdb: REMOVED
apikey.acoustid: REMOVED
apikey.anidb: filebot
apikey.opensubtitles:
```

I've removed the above API keys in case rednoah doesn't want them posted here but you can find all the API keys in the various junit test classes (in `/test/net/filebot/web/`).

**Comment by rednoah** [comment]
Preferably, you should use your own API keys in your own builds.
