### ISSUE TITLE
[v4.7.5] High CPU & Memory usage when fetching metadata

### ISSUE THREAD

**Issue by computerfr33k** [filebot/filebot#5]
OS: ArchLinux x64

When I try and match a file using tvdb or themoviedb it sits there doing nothing while taking large amounts of resources and the only way to kill it is with a `kill -9 $PID`. While I let it sit there, the UI is also unusable.

When I launched it using the terminal I got the following output when it was searching for the metadata
```bash
Owner failed to convert data
java.io.IOException: Owner failed to convert data
        at net.filebot.ui.transfer.FileTransferable.getFilesFromTransferable(FileTransferable.java:130)
        at net.filebot.ui.transfer.FileTransferablePolicy.accept(FileTransferablePolicy.java:17)
        at net.filebot.ui.transfer.TransferablePolicy.canImport(TransferablePolicy.java:24)
        at net.filebot.ui.transfer.DefaultTransferHandler.canImport(DefaultTransferHandler.java:40)
```

**Comment by rednoah** [comment]
I don't think this error message has anything to do with the error you describe.

**Comment by rednoah** [comment]
Also, a post in the forums with some sysinfo would be nice if somebody else is having the same issue: https://www.filebot.net/forums/viewtopic.php?f=6&t=1868
