### ISSUE TITLE
issue when attempting to open Filebot with Java 11

### ISSUE THREAD

**Issue by elgallo** [filebot/filebot#59]
when opening filebot from applications folder I get this error

<img width="417" alt="screen shot 2019-01-15 at 12 24 34 am" src="https://user-images.githubusercontent.com/9777026/51167664-f996a200-185b-11e9-9765-7ba19fca0286.png">

yet my system has Java 11 (Oracle no longer supports 10 and am unable to download)

<img width="515" alt="screen shot 2019-01-15 at 12 23 40 am" src="https://user-images.githubusercontent.com/9777026/51167742-264ab980-185c-11e9-9beb-abd60e5c7ad1.png">

when I run
 `$filebot`

I get the following error in terminal

````
filebot                                                         00:21:09
Failed to initialize JavaFX
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
        at net.filebot.util.ui.SwingUI.initJavaFX(SwingUI.java:519)
        at net.filebot.Main.onStart(Main.java:191)
        at net.filebot.Main.lambda$main$1(Main.java:161)
        at net.filebot.util.ui.SwingUI$SwingRunnable.doInBackground(SwingUI.java:435)
        at net.filebot.util.ui.SwingUI$SwingRunnable.doInBackground(SwingUI.java:425)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        ... 5 more
````
though I can use the GUI from terminal I prefer CLI. If I attempt to open the my license file either by double clicking or `open with` filebot I still get the error that I need java 10 or higher

**Comment by rednoah** [comment]
What package are you using? Please use the `macOS installer: FileBot_4.8.2.pkg` package. It's self-contained and has no dependencies.
https://www.filebot.net/#download
