### ISSUE TITLE
Doens't rename under Linux!

### ISSUE THREAD

**Issue by mbnoimi** [filebot/filebot#9]
Whenever I try to rename files using Filbot I get ```class not found``` error!

* Linux Mint 18 x64 xfce
* FileBot 4.7.7

Terminal run:
```
mbnoimi@mbnoimi-laptop ~ $ filebot --log-file /home/mbnoimi/Desktop/log.txt --log all
Failed to initialize JavaFX. Please install JavaFX.
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at net.filebot.util.ui.SwingUI.initJavaFX(SwingUI.java:510)
	at net.filebot.Main.onStart(Main.java:159)
	at net.filebot.Main.lambda$null$0(Main.java:134)
	at net.filebot.util.ui.SwingUI$SwingRunnable.doInBackground(SwingUI.java:426)
	at net.filebot.util.ui.SwingUI$SwingRunnable.doInBackground(SwingUI.java:416)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	... 5 more

ClassNotFoundException: javafx.concurrent.Task
java.lang.NoClassDefFoundError: javafx/concurrent/Task
	at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(RenameAction.java:91)
	at net.filebot.util.ui.SwingUI.withWaitCursor(SwingUI.java:324)
	at net.filebot.ui.rename.RenameAction.actionPerformed(RenameAction.java:69)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
	... 3 more

mbnoimi@mbnoimi-laptop ~ $ 
```

log.txt
```
Failed to initialize JavaFX. Please install JavaFX.
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at net.filebot.util.ui.SwingUI.initJavaFX(SwingUI.java:510)
	at net.filebot.Main.onStart(Main.java:159)
	at net.filebot.Main.lambda$null$0(Main.java:134)
	at net.filebot.util.ui.SwingUI$SwingRunnable.doInBackground(SwingUI.java:426)
	at net.filebot.util.ui.SwingUI$SwingRunnable.doInBackground(SwingUI.java:416)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	... 5 more

ClassNotFoundException: javafx.concurrent.Task
java.lang.NoClassDefFoundError: javafx/concurrent/Task
	at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(RenameAction.java:91)
	at net.filebot.util.ui.SwingUI.withWaitCursor(SwingUI.java:324)
	at net.filebot.ui.rename.RenameAction.actionPerformed(RenameAction.java:69)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
	... 3 more
```

**Comment by rednoah** [comment]
Please install JavaFX.

**Comment by shillshocked** [comment]
Didn't work on Arch, even after installing it.

**Comment by rednoah** [comment]
Please report the issue to the OpenJDK / OpenJFX package maintainers for Arch.
